# -*- coding: utf-8 -*-
"""andx_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z01GaS_t25RubFYQDi1UbKQZ8Hnb-LVT

# Audionyx: Real-Time Audio Deepfake Detection Pipeline

**System Version:** 2.0 (Telephony/VoIP Optimized)
**Target Environment:** Google Colab (GPU)

This pipeline implements a defense-grade audio deepfake detection system designed specifically for the low-fidelity, high-noise environment of phone calls and VoIP systems.

## Core Modules:
1.  **Telephony-Specific Augmentation**: Simulates GSM/AMR codecs and bandpass filtering.
2.  **Robust Preprocessing**: Spectral gating denoising and VAD.
3.  **Hybrid Feature Extraction**: Stacking Mel-Spectrograms and LFCCs.
4.  **Dual-Stage Model**: Low-latency CNN (Early Exit) + Context-aware Transformer.
5.  **Stable Decision Logic**: Hysteresis thresholding to prevent UI flickering.
6.  **VoIP Security Demo**: Interactive Gradio interface.
"""

# 1.1 Dataset Import (KaggleHub Method)
import os

try:
    import kagglehub
except ImportError:
    print("Installing kagglehub...")
    !pip install kagglehub -q
    import kagglehub

print("Downloading dataset via KaggleHub...")
# NOTE: This may prompt you to login to Kaggle if you haven't configured credentials.
# If it asks, just follow the link it provides to get your API key.
downloaded_path = kagglehub.dataset_download('mohammedabdeldayem/the-fake-or-real-dataset')

print(f"✅ Data source import complete.")
print(f"Local Path: {downloaded_path}")

# Quick verify of structure
print("\nVerifying dataset structure...")
for root, dirs, files in os.walk(downloaded_path):
    level = root.replace(downloaded_path, '').count(os.sep)
    indent = ' ' * 4 * (level)
    print(f"{indent}{os.path.basename(root)}/")
    subindent = ' ' * 4 * (level + 1)
    # Print first few files only
    for f in files[:3]:
        print(f"{subindent}{f}")
    if len(files) > 3:
        print(f"{subindent}... ({len(files)-3} more files)")
    if level > 1: break # Limit depth for cleanliness

# 1. Environment Setup & Dependencies
# Install specific audio processing and UI libraries
!pip install torchaudio librosa noisereduce gradio scipy soundfile numpy matplotlib -q

import torch
import torch.nn as nn
import torch.nn.functional as F
import torchaudio
import torchaudio.transforms as T
import torchaudio.functional as AF
import librosa
import noisereduce as nr
import numpy as np
import random
import gradio as gr
from collections import deque
from scipy.signal import butter, lfilter

print(f"PyTorch Version: {torch.__version__}")
print(f"GPU Available: {torch.cuda.is_available()}")
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# 2. Telephony-Specific Data Augmentation (The "Domain Gap" Fix)

class TelephonyAugment:
    """
    Simulates 'In-The-Wild' phone call conditions to bridge the domain gap between
    clean training data and real-world VoIP/GSM audio.
    """
    def __init__(self, sample_rate=16000):
        self.sample_rate = sample_rate
        # Standard telephony bandpass
        self.low_freq = 300
        self.high_freq = 3400

    def apply_narrowband(self, waveform):
        """Applies 300Hz-3400Hz Bandpass Filter"""
        return AF.bandpass_biquad(waveform, self.sample_rate, central_freq=1850, Q=0.6)

    def apply_codec_simulation(self, waveform):
        """
        Simulates GSM/AMR quality by downsampling to 8kHz and upsampling back.
        This creates the aliasing and high-frequency loss typical of phone lines.
        """
        downsampler = T.Resample(self.sample_rate, 8000).to(waveform.device)
        upsampler = T.Resample(8000, self.sample_rate).to(waveform.device)

        downsampled = downsampler(waveform)
        restored = upsampler(downsampled)
        return restored

    def inject_noise(self, waveform, noise_level=0.005):
        """Injects random Gaussian noise (simulating line static)"""
        noise = torch.randn_like(waveform) * noise_level
        return waveform + noise

    def __call__(self, waveform):
        # 1. Bandpass (Narrowband)
        aug_wav = self.apply_narrowband(waveform)

        # 2. Codec Simulation (GSM-like)
        aug_wav = self.apply_codec_simulation(aug_wav)

        # 3. Noise Injection
        if random.random() > 0.5:
             aug_wav = self.inject_noise(aug_wav)

        return aug_wav

# Test the augmentation
telephony_aug = TelephonyAugment(sample_rate=16000)
print("Telephony Augmentation Module Initialized")

# 3. Robust Preprocessing (The "False Positive" Fix)

class AudioPreprocessor:
    """
    Cleans audio stream and filters out silence/non-speech to prevent false positives
    triggered by background noise (e.g., car horns, typing).
    """
    def __init__(self, sample_rate=16000, vad_threshold_db=20):
        self.sample_rate = sample_rate
        self.vad_threshold_db = vad_threshold_db

    def suppress_noise(self, audio_numpy):
        """
        Uses spectral gating to remove stationary noise.
        Input: numpy array (C, T) or (T,)
        """
        # noisereduce expects (C, T) or (T,)
        # For simple streaming, we assume stationary noise profile estimated from first few frames
        # Here we use a fast stationary approximation
        try:
            cleaned = nr.reduce_noise(y=audio_numpy, sr=self.sample_rate, stationary=True, prop_decrease=0.75)
            return cleaned
        except Exception as e:
            # Fallback if noise reduction fails (e.g. too short)
            return audio_numpy

    def is_speech_active(self, waveform):
        """
        Simple Energy-based VAD.
        Returns True if RMS energy > threshold.
        """
        # Convert to DB
        rms = torch.sqrt(torch.mean(waveform ** 2))
        db = 20 * torch.log10(rms + 1e-9)

        # Threshold check (relative to full scale or calibrated background)
        # In normalized wav (-1 to 1), -40dB is a reasonable silence floor
        return db > -40.0 # Strict check, adjustable

    def process(self, waveform):
        """
        Full pipeline: Tensor -> Numpy -> Denoise -> Tensor -> VAD Check
        Result: (processed_waveform, is_active)
        """
        # 1. Convert to numpy for noisereduce library
        wav_np = waveform.cpu().numpy()

        # 2. Denoise
        if len(wav_np.shape) > 1:
            wav_np = wav_np[0] # Take first channel for mono proc

        clean_np = self.suppress_noise(wav_np)
        clean_tensor = torch.from_numpy(clean_np).unsqueeze(0).to(waveform.device).float()

        # 3. VAD
        is_active = self.is_speech_active(clean_tensor)

        return clean_tensor, is_active

preprocessor = AudioPreprocessor()
print("Audio Preprocessor Initialized")

# 4. Feature Extraction (The "Hybrid" Input)
import torch
import torch.nn as nn
import torchaudio.transforms as T

# Safety check: Define 'device' if this cell is run standalone
if 'device' not in globals():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"⚠️ Note: 'device' was missing. Auto-set to: {device}")

class HybridFeatureExtractor(nn.Module):
    """
    Extracts and stacks Mel-Spectrograms (spatial/timbre) and LFCCs (phase/voice characteristics).
    Optimized for short streaming windows.
    """
    def __init__(self, sample_rate=16000, n_mels=64, n_lfcc=64):
        super().__init__()
        self.mel_transform = T.MelSpectrogram(
            sample_rate=sample_rate,
            n_mels=n_mels,
            n_fft=400,
            win_length=400,
            hop_length=160
        )

        # Fixed: LFCC expects STFT kwargs in a dictionary named 'speckwargs'
        self.lfcc_transform = T.LFCC(
            sample_rate=sample_rate,
            n_lfcc=n_lfcc,
            speckwargs={
                "n_fft": 400,
                "win_length": 400,
                "hop_length": 160
            }
        )

    def forward(self, waveform):
        # 1. Extract Mel-Spectrogram
        # Shape: (Batch, n_mels, Time)
        mels = self.mel_transform(waveform)
        mels = T.AmplitudeToDB()(mels) # Log scale

        # 2. Extract LFCC
        # Shape: (Batch, n_lfcc, Time)
        lfccs = self.lfcc_transform(waveform)

        # 3. Normalization (Simple instance norm for robustness)
        mels = (mels - mels.mean()) / (mels.std() + 1e-6)
        lfccs = (lfccs - lfccs.mean()) / (lfccs.std() + 1e-6)

        # 4. Stack features
        # We treat Mel and LFCC as 2 separate channels for the CNN
        # Shape: (Batch, 2, Freq_Bins, Time)
        # Note: Freq_Bins = n_mels = n_lfcc
        combined = torch.stack([mels, lfccs], dim=1)

        return combined

feature_extractor = HybridFeatureExtractor().to(device)
print("Hybrid Feature Extractor Initialized")

# 5. Model Architecture: CNN-Transformer with "Early Exit" (The Latency Fix)

class DeepfakeDetector(nn.Module):
    def __init__(self, num_classes=2):
        super().__init__()

        # Stage 1: Lightweight CNN (Feature Extractor)
        # Input: (Batch, 2 channels, 64 freq, Time)
        self.cnn = nn.Sequential(
            nn.Conv2d(2, 16, kernel_size=3, padding=1),
            nn.BatchNorm2d(16),
            nn.ReLU(),
            nn.MaxPool2d(2, 2), # -> (16, 32, Time/2)

            nn.Conv2d(16, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.MaxPool2d(2, 2), # -> (32, 16, Time/4)

            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(2, 2)  # -> (64, 8, Time/8)
        )

        # Compute dimension after CNN
        # For a 200ms chunk (approx 3200 samples -> ~20 frames mel)
        # Time dim reduces: 20 -> 10 -> 5 -> 2

        # Stage 2: Early Exit (Latency < 50ms)
        self.early_exit_gap = nn.AdaptiveAvgPool2d(1)
        self.early_exit_head = nn.Linear(64, 1) # Binary regression (0-1)

        # Stage 3: Transformer (Context Aggregator)
        self.projection = nn.Linear(64 * 8, 128) # Flatten freq dimension
        encoder_layer = nn.TransformerEncoderLayer(d_model=128, nhead=4, dim_feedforward=256, batch_first=True)
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=2)

        # Stage 4: Final Head (Stable Decision)
        self.final_head = nn.Sequential(
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(64, 1) # Binary regression (0-1)
        )

    def forward(self, x):
        # x: (Batch, 2, 64, Time)

        # 1. CNN Features
        features_2d = self.cnn(x) # (Batch, 64, 8, Reduced_Time)

        # 2. Early Exit Path
        # Global Average Pooling for instant snapshot
        pooled_early = self.early_exit_gap(features_2d).flatten(1)
        early_score = torch.sigmoid(self.early_exit_head(pooled_early))

        # 3. Transformer Prep
        # Permute to (Batch, Time, Channels*Freq)
        batch, ch, freq, time = features_2d.shape
        features_seq = features_2d.permute(0, 3, 1, 2).reshape(batch, time, ch * freq)

        # Project to d_model
        projected = self.projection(features_seq)

        # 4. Transformer Context features
        context_features = self.transformer(projected)

        # Pool over time for final decision (take mean of sequence)
        context_pooled = context_features.mean(dim=1)

        # 5. Final Decision
        final_score = torch.sigmoid(self.final_head(context_pooled))

        return early_score, final_score

model = DeepfakeDetector().to(device)
print(f"Model Architecture Built. Parameters: {sum(p.numel() for p in model.parameters())}")

# 6. Post-Processing UX Logic (The "Anti-Flicker" Fix)

class StableDecisionMaker:
    """
    Prevents UI flickering by using hysteresis and smoothing.
    """
    def __init__(self, history_len=5, high_threshold=0.85, low_threshold=0.60):
        self.history = deque(maxlen=history_len)
        self.high_threshold = high_threshold
        self.low_threshold = low_threshold
        self.current_state = "SAFE" # SAFE or THREAT

    def update(self, new_score):
        # 1. Add to rolling window
        self.history.append(new_score)

        # 2. Median Filter (Smooth out outliers)
        smoothed_score = np.median(self.history)

        # 3. Hysteresis Logic
        if self.current_state == "SAFE":
            if smoothed_score > self.high_threshold:
                self.current_state = "THREAT"
        else: # Currently in THREAT state
            if smoothed_score < self.low_threshold:
                self.current_state = "SAFE"

        return self.current_state, smoothed_score

decision_maker = StableDecisionMaker()
print("Stable Decision Logic Ready")

"""## 8. Training Pipeline

Since you have the dataset on your PC, you'll need to point the data loader to your local directories.

**Dataset Structure Expectation:**
Ensure your dataset is organized like this:
```
/path/to/dataset/
    ├── real/
    │   ├── real_call_001.wav
    │   └── ...
    └── fake/
        ├── fake_generated_001.wav
        └── ...
```

This section implements:
1. **Custom Dataset Loader**: Reads audio files, applies the `TelephonyAugment`, and prepares fixed-length chunks.
2. **Dual-Loss Training Loop**: optimize both the "Early Exit" and "Final Head" simultaneously.
"""

from torch.utils.data import Dataset, DataLoader
import os
import glob
import librosa # Ensure librosa is available for fallback

class DeepfakeDataset(Dataset):
    def __init__(self, root_dir, max_samples=None, transform=None, target_sample_rate=16000, duration_sec=4):
        """
        Args:
            root_dir (str): Path to dataset root containing 'real' and 'fake' subfolders.
            max_samples (int): Limit number of files for quick debugging.
            transform (callable): Augmentation function (TelephonyAugment).
            duration_sec (int): Fixed duration to pad/truncate audio to.
        """
        self.root_dir = root_dir
        self.transform = transform
        self.target_sample_rate = target_sample_rate
        self.num_samples = int(target_sample_rate * duration_sec)

        # Load file paths
        self.real_files = glob.glob(os.path.join(root_dir, 'real', '*.*'))
        self.fake_files = glob.glob(os.path.join(root_dir, 'fake', '*.*'))

        if max_samples:
            self.real_files = self.real_files[:max_samples]
            self.fake_files = self.fake_files[:max_samples]

        # Create (filepath, label) tuples. Label: 0=Real, 1=Fake (standard convention)
        self.file_list = [(f, 0.0) for f in self.real_files] + [(f, 1.0) for f in self.fake_files]
        random.shuffle(self.file_list)

        print(f"Found {len(self.real_files)} Real and {len(self.fake_files)} Fake samples.")

    def __len__(self):
        return len(self.file_list)

    def __getitem__(self, idx):
        filepath, label = self.file_list[idx]

        try:
            # Robust Audio Loading
            # Problem: Some files trigger "TorchCodec" errors or are encoded strangely.
            # Solution: Try native torchaudio, fallback to librosa (FFmpeg-based).
            try:
                waveform, sr = torchaudio.load(filepath)
            except Exception:
                # Fallback: using librosa which is more robust to format issues
                y, sr = librosa.load(filepath, sr=None, mono=False)

                # Ensure shape is (Channels, Time)
                if y.ndim == 1:
                    y = y[np.newaxis, :]

                waveform = torch.from_numpy(y).float()

            # Resample if needed
            if sr != self.target_sample_rate:
                resampler = T.Resample(sr, self.target_sample_rate)
                waveform = resampler(waveform)

            # Mix to mono
            if waveform.shape[0] > 1:
                waveform = torch.mean(waveform, dim=0, keepdim=True)

            # Pad or Truncate to fixed length
            if waveform.shape[1] < self.num_samples:
                # Pad
                padding = self.num_samples - waveform.shape[1]
                waveform = F.pad(waveform, (0, padding))
            else:
                # Random Crop
                start = random.randint(0, waveform.shape[1] - self.num_samples)
                waveform = waveform[:, start:start+self.num_samples]

            # Apply Augmentation (Telephony Effects)
            if self.transform:
                waveform = self.transform(waveform)

            return waveform, torch.tensor([label], dtype=torch.float32)

        except Exception as e:
            # Only print error if it's NOT the common load error we just handled
            print(f"Failed to load {os.path.basename(filepath)}: {e}")
            # Return a generic silence tensor to prevent crashing
            return torch.zeros((1, self.num_samples)), torch.tensor([label], dtype=torch.float32)

print("Dataset Class Defined")

def train_audionyx(model, train_loader, val_loader, epochs=10, lr=1e-4, patience=3):
    """
    Training loop with Early Stopping:
    - Saves 'audionyx_model.pt' whenever validation loss improves.
    - AUTOMATICALLY restores the best weights at the end of training.
    """
    criterion = nn.BCELoss() # Binary Cross Entropy
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)

    # Weights for the loss: Prioritize accuracy of the final transformer head
    loss_weight_early = 0.4
    loss_weight_final = 1.0

    # Early Stopping Variables
    best_val_loss = float('inf')
    patience_counter = 0
    best_model_path = "audionyx_model.pt"

    for epoch in range(epochs):
        model.train()
        total_loss = 0
        correct_final = 0
        total_samples = 0

        print(f"\nEpoch {epoch+1}/{epochs}")
        print("-" * 20)

        for batch_idx, (waveform, label) in enumerate(train_loader):
            waveform, label = waveform.to(device), label.to(device)
            if waveform.dim() == 2: waveform = waveform.unsqueeze(1)

            features = feature_extractor(waveform.squeeze(1))
            early_prob, final_prob = model(features)

            loss_early = criterion(early_prob, label)
            loss_final = criterion(final_prob, label)
            loss = (loss_weight_early * loss_early) + (loss_weight_final * loss_final)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            total_loss += loss.item()
            preds = (final_prob > 0.5).float()
            correct_final += (preds == label).sum().item()
            total_samples += label.size(0)

            if batch_idx % 50 == 0:
                print(f"Batch {batch_idx}: Loss {loss.item():.4f}")

        avg_train_loss = total_loss / len(train_loader)
        train_acc = correct_final / total_samples
        print(f"Train Loss: {avg_train_loss:.4f} | Train Acc: {train_acc*100:.2f}%")

        # Validation & Early Stopping Check
        if val_loader:
            val_loss, val_acc = validate(model, val_loader, criterion)

            if val_loss < best_val_loss:
                print(f"✅ Validation improved ({best_val_loss:.4f} -> {val_loss:.4f}). Saving model...")
                best_val_loss = val_loss
                patience_counter = 0
                torch.save(model.state_dict(), best_model_path)
            else:
                patience_counter += 1
                print(f"⚠️ No improvement. Patience: {patience_counter}/{patience}")

            if patience_counter >= patience:
                print(f"🛑 Early Stopping Triggered! Stopping now.")
                break

    # Always ensure the model in memory matches the best saved file
    print(f"\nTraining Complete. Reloading best weights from '{best_model_path}'...")
    model.load_state_dict(torch.load(best_model_path))

def validate(model, loader, criterion):
    model.eval()
    val_loss = 0
    correct = 0
    total = 0

    with torch.no_grad():
        for waveform, label in loader:
            waveform, label = waveform.to(device), label.to(device)
            features = feature_extractor(waveform.squeeze(1))
            _, final_prob = model(features)

            loss = criterion(final_prob, label)
            val_loss += loss.item()
            preds = (final_prob > 0.5).float()
            correct += (preds == label).sum().item()
            total += label.size(0)

    avg_loss = val_loss / len(loader)
    acc = correct / total
    print(f"Val Loss: {avg_loss:.4f} | Val Acc: {acc*100:.2f}%")
    return avg_loss, acc

print("Training Functions Updated: Now Includes Auto-Save Best & Early Stopping")

# --- CONFIGURATION & EXECUTION ---

# Dataset Version Selection
# The downloaded dataset has multiple versions.
# "for-norm" is usually best for training stable models.
# Options: "for-norm", "for-original", "for-2sec", "for-rerec"
SELECTED_VERSION = "for-norm"

# Auto-configure path based on previous cell
if 'downloaded_path' in globals():
    # Use the variable from Cell 4
    BASE_SEARCH_PATH = downloaded_path
    print(f"Searching for '{SELECTED_VERSION}' in downloaded path: {BASE_SEARCH_PATH}")
elif os.path.exists("/content/dataset_uploaded"):
    BASE_SEARCH_PATH = "/content/dataset_uploaded"
    print(f"Searching for '{SELECTED_VERSION}' in manual upload path: {BASE_SEARCH_PATH}")
else:
    BASE_SEARCH_PATH = "/content"
    print("⚠️ No specific dataset path found. Using root /content")

DATA_PATH = None

if os.path.exists(BASE_SEARCH_PATH):
    # Search for the specific selected version folder
    # We look for a path ending in /for-norm/for-norm/training OR /for-norm/training
    found_train = None

    for root, dirs, files in os.walk(BASE_SEARCH_PATH):
        if 'training' in dirs:
            # Check if this training folder belongs to our selected version
            if SELECTED_VERSION in root:
                found_train = os.path.join(root, 'training')
                # If we find the nested structure (for-norm/for-norm), prefer it
                if os.path.join(SELECTED_VERSION, SELECTED_VERSION) in root:
                     break
                # Otherwise keep looking in case there's a better match, or accept this one

    if found_train:
         DATA_PATH = os.path.dirname(found_train) # Parent of training/ is our DATA_PATH
         print(f"✅ Found correct dataset version at: {DATA_PATH}")
    else:
         # Fallback: Just find ANY training folder
         for root, dirs, files in os.walk(BASE_SEARCH_PATH):
             if 'training' in dirs:
                 DATA_PATH = root
                 print(f"⚠️ specific '{SELECTED_VERSION}' not found, falling back to: {DATA_PATH}")
                 break

if DATA_PATH and os.path.exists(DATA_PATH):
    # Paths to subfolders
    train_dir = os.path.join(DATA_PATH, 'training')
    val_dir = os.path.join(DATA_PATH, 'validation')

    # Initialize Datasets
    print("\n--- Process Training Data ---")
    train_dataset = DeepfakeDataset(
        root_dir=train_dir,
        transform=telephony_aug,
        duration_sec=4
    )

    print("\n--- Process Validation Data ---")
    val_dataset = DeepfakeDataset(
        root_dir=val_dir,
        transform=None,
        duration_sec=4
    )

    if len(train_dataset) > 0:
        # Data Loaders
        train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True, num_workers=2)
        val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False, num_workers=2)

        print(f"\nLocked & Loaded:")
        print(f"Training Samples: {len(train_dataset)}")
        print(f"Validation Samples: {len(val_dataset)}")

        print("\nStarting Training Pipeline...")
        # Train
        train_audionyx(model, train_loader, val_loader, epochs=10)

        # Save Model
        torch.save(model.state_dict(), "audionyx_model.pt")
        print("\nModel saved as 'audionyx_model.pt'")

        # Optional: Run on Test Set
        # Typically 'testing' is sibling to 'training'
        test_dir = os.path.join(DATA_PATH, 'testing')
        if os.path.exists(test_dir):
            print("\n--- Running Final Test Set Evaluation ---")
            test_dataset = DeepfakeDataset(test_dir, transform=None, duration_sec=4)
            test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)
            validate(model, test_loader, nn.BCELoss())

    else:
        print("Error: Datasets appear empty. Check folder structure.")
else:
    print(f"❌ Dataset not found at expected locations.")
    print("Action: Run the Import Cell (1.1) above.")

# --- COLAB ONLY: Save Model Permanently ---
# IMPORTANT: In Google Colab, files are DELETED when the runtime disconnects.
# Run this cell to download the model to your PC or save it to Google Drive.

import os
import shutil

if 'google.colab' in str(get_ipython()):
    print("⚠️ Detected Google Colab Environment")

    if os.path.exists("audionyx_model.pt"):
        print(f"Model file found. Size: {os.path.getsize('audionyx_model.pt') / 1024 / 1024:.2f} MB")

        # Option 1: Download to local machine
        print("⬇️ Triggering download to your local PC...")
        from google.colab import files
        files.download('audionyx_model.pt')

        # Option 2: Save to Google Drive (Uncomment to use)
        # from google.colab import drive
        # drive.mount('/content/drive')
        # shutil.copy("audionyx_model.pt", "/content/drive/MyDrive/audionyx_model.pt")
        # print("✅ Copied to Google Drive (My Drive root)")
    else:
        print("❌ 'audionyx_model.pt' not found. Train the model first!")
else:
    print("✅ You are running locally. The file is already safe on your hard drive.")

# 8.1 Detailed Performance Evaluation
import time
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, roc_auc_score, roc_curve, ConfusionMatrixDisplay
)
import matplotlib.pyplot as plt

def evaluate_performance(model, loader, device):
    model.eval()
    y_true = []
    y_pred = []
    y_scores = []
    latencies = []

    print("running comprehensive evaluation...")

    with torch.no_grad():
        for waveform, label in loader:
            waveform = waveform.to(device)
            # Ensure proper dimensions (Batch, Channel, Time)
            if waveform.dim() == 2: waveform = waveform.unsqueeze(1)

            # Start timer for latency
            start_time = time.time()

            # Forward pass
            features = feature_extractor(waveform.squeeze(1))
            _, final_prob = model(features)

            # End timer
            end_time = time.time()

            # Record latency (ms) per batch - divided by batch size for per-sample estimate
            batch_size = waveform.size(0)
            latencies.append((end_time - start_time) * 1000 / batch_size)

            # Store results
            y_true.extend(label.cpu().numpy().flatten())
            y_scores.extend(final_prob.cpu().numpy().flatten())
            y_pred.extend((final_prob > 0.5).cpu().numpy().flatten().astype(int))

    # Metric Calculations
    acc = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred)
    rec = recall_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred)

    try:
        auc = roc_auc_score(y_true, y_scores)

        # EER Calculation
        fpr, tpr, thresholds = roc_curve(y_true, y_scores)
        fnr = 1 - tpr
        # EER is where FPR crosses FNR
        eer_threshold = thresholds[np.nanargmin(np.absolute((fnr - fpr)))]
        eer = fpr[np.nanargmin(np.absolute((fnr - fpr)))]
    except ValueError:
        auc = 0.5
        eer = 0.5
        eer_threshold = 0.5
        print("⚠️ Warning: Could not calculate ROC/EER (likely only one class present in subset)")

    avg_latency = np.mean(latencies)

    # Report
    print("\n" + "="*40)
    print("🔍 MODEL PERFORMANCE REPORT")
    print("="*40)
    print(f"✅ Accuracy:          {acc:.4f} ({acc*100:.2f}%)")
    print(f"🎯 Precision:         {prec:.4f}")
    print(f"🕵️ Recall:            {rec:.4f}")
    print(f"⚖️ F1-Score:          {f1:.4f}")
    print(f"📈 ROC-AUC:           {auc:.4f}")
    print(f"⚙️ EER (Equal Error): {eer:.4f} (Threshold: {eer_threshold:.4f})")
    print(f"⚡ Avg Latency:       {avg_latency:.2f} ms/sample")
    print("="*40)

    # Visualization: Confusion Matrix
    cm = confusion_matrix(y_true, y_pred)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Real", "Deepfake"])

    fig, ax = plt.subplots(1, 2, figsize=(12, 5))

    # Plot Confusion Matrix
    disp.plot(ax=ax[0], cmap='Blues', values_format='d')
    ax[0].set_title("Confusion Matrix")

    # Plot ROC Curve
    if 'fpr' in locals():
        ax[1].plot(fpr, tpr, label=f"AUC = {auc:.2f}")
        ax[1].plot([0, 1], [0, 1], 'k--')
        ax[1].set_xlabel("False Positive Rate")
        ax[1].set_ylabel("True Positive Rate")
        ax[1].set_title("ROC Curve")
        ax[1].legend()

    plt.tight_layout()
    plt.show()

# Run evaluation on Validation Set
if 'val_loader' in globals() and model:
    evaluate_performance(model, val_loader, device)
else:
    print("⚠️ Validation loader or model not found. Run training cell (Cell 12) first.")

# --- GPU VERIFICATION ---
import torch

if torch.cuda.is_available():
    print(f"✅ GPU is Online: {torch.cuda.get_device_name(0)}")

    # Check if model is actually on the GPU
    model_device = next(model.parameters()).device
    if model_device.type == 'cuda':
        print(f"✅ Model is successfully loaded on: {model_device}")
    else:
        print(f"⚠️ Model is currently on: {model_device} (Should be cuda:0)")
        model = model.to('cuda')
        print("   -> Moved model to GPU.")

    print(f"Current Memory Usage: {torch.cuda.memory_allocated()/1024**2:.2f} MB")
else:
    print("❌ GPU is NOT available.")
    print("Action Required: Go to 'Runtime' > 'Change runtime type' > Select 'T4 GPU'")

"""## 9. Live Demo (Run After Training)
Now that the model is trained, use this interactive interface to test it with your voice.
"""

# 7. The "VoIP Security Layer" Demo (The Pivot)

def run_audionyx_pipeline(audio_path):
    """
    Wrapper for Gradio to run the full pipeline on a microphone chunk.
    Audio comes in as a filepath (lighter on the browser than raw numpy).
    """
    if audio_path is None:
        return "Waiting...", "Waiting...", 0.0

    try:
        # Load audio using librosa (Standardizes sample rate instantly)
        # We load directly to 16k to save processing time
        y, sr = librosa.load(audio_path, sr=16000)
    except Exception as e:
        return f"Error: {str(e)}", "Error", 0.0

    # Create tensor
    raw_tensor = torch.from_numpy(y).float().to(device)

    # --- PIPELINE START ---

    # 1. Preprocessing (Noise & VAD)
    clean_tensor, is_speech = preprocessor.process(raw_tensor)

    if not is_speech:
        return "Silence Detected", "standby...", 0.0

    # Check length (prevent crash on very short blips)
    if clean_tensor.shape[-1] < 400:
         return "Audio too short", "standby...", 0.0

    # 2. Feature Extraction
    # Ensure batched input (Batch, Channel, Time) -> (1, Time)
    if clean_tensor.dim() == 1:
        clean_tensor = clean_tensor.unsqueeze(0)

    features = feature_extractor(clean_tensor)

    # 3. Model Inference
    model.eval()
    with torch.no_grad():
        # returns (early_exit, final)
        pre_warning, final_raw = model(features)

    pre_score = pre_warning.item()
    final_score = final_raw.item()

    # 4. Stable Decision
    state, smoothed_score = decision_maker.update(final_score)

    # --- PIPELINE END ---

    # Formatting Output
    early_exit_ui = f"⚠️ Risk: {pre_score:.2f}" if pre_score > 0.7 else "✅ Low Risk"
    final_ui = "🚨 DEEPFAKE DETECTED" if state == "THREAT" else "🛡️ Voice Verified"

    return early_exit_ui, final_ui, smoothed_score

# Create Gradio Interface
# OPTIMIZATION: type="filepath" prevents browser crashes
demo = gr.Interface(
    fn=run_audionyx_pipeline,
    inputs=gr.Audio(sources=["microphone", "upload"], type="filepath", label="Simulate VoIP Call"),
    outputs=[
        gr.Textbox(label="Stage 1: Instant Risk (Early Exit)"),
        gr.Textbox(label="Stage 2: Confirmed Threat (Transformer)"),
        gr.Number(label="Smoothed Confidence Score")
    ],
    title="Audionyx: VoIP Security Layer",
    description="Real-time Deepfake Detection Pipeline. Record a voice clip to test.",
    flagging_mode="never"
)

print("Launch the cell below to start the demo app!")

# --- ROBUST COLAB LAUNCHER ---

# 1. Close any hanging instances first (Fixes "Not Responding")
try:
    demo.close()
    print("Checked for existing servers.")
except:
    pass

print("🚀 Starting VoIP Security Layer Demo...")
print("⏳ Please wait for the 'Running on public URL' link to appear below...")

# 2. Launch with robust parameters
# inline=False: Forces a link instead of a tiny frame (better stability)
# share=True: Creates the public tunnel required for Colab
demo.queue().launch(
    share=True,
    debug=True,
    inline=False
)

# NOTE: This cell will keep "running" (spinning) as long as the server is active.
# Do NOT stop this cell unless you want to shut down the website.